# Generated by Django 4.2.4 on 2023-10-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='perfume',
        ),
    ]
